/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MisAnunciosRouteImport } from './routes/mis-anuncios'
import { Route as OfertasRouteImport } from './routes/ofertas'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PublicarRouteImport } from './routes/publicar'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAnunciosRouteImport } from './routes/admin/anuncios'
import { Route as AdminContactosRouteImport } from './routes/admin/contactos'
import { Route as AdminOfertasRouteImport } from './routes/admin/ofertas'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as VehiculoIdRouteImport } from './routes/vehiculo.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MisAnunciosRoute = MisAnunciosRouteImport.update({
  id: '/mis-anuncios',
  path: '/mis-anuncios',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasRoute = OfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarRoute = PublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnunciosRoute = AdminAnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactosRoute = AdminContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOfertasRoute = AdminOfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const VehiculoIdRoute = VehiculoIdRouteImport.update({
  id: '/vehiculo/$id',
  path: '/vehiculo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/mis-anuncios': typeof MisAnunciosRoute
  '/ofertas': typeof OfertasRoute
  '/perfil': typeof PerfilRoute
  '/publicar': typeof PublicarRoute
  '/terminos': typeof TerminosRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/contactos': typeof AdminContactosRoute
  '/admin/ofertas': typeof AdminOfertasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/vehiculo/$id': typeof VehiculoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/mis-anuncios': typeof MisAnunciosRoute
  '/ofertas': typeof OfertasRoute
  '/perfil': typeof PerfilRoute
  '/publicar': typeof PublicarRoute
  '/terminos': typeof TerminosRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/contactos': typeof AdminContactosRoute
  '/admin/ofertas': typeof AdminOfertasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/vehiculo/$id': typeof VehiculoIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/mis-anuncios': typeof MisAnunciosRoute
  '/ofertas': typeof OfertasRoute
  '/perfil': typeof PerfilRoute
  '/publicar': typeof PublicarRoute
  '/terminos': typeof TerminosRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/contactos': typeof AdminContactosRoute
  '/admin/ofertas': typeof AdminOfertasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/vehiculo/$id': typeof VehiculoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalogo'
    | '/contacto'
    | '/favoritos'
    | '/login'
    | '/mis-anuncios'
    | '/ofertas'
    | '/perfil'
    | '/publicar'
    | '/terminos'
    | '/admin/anuncios'
    | '/admin/contactos'
    | '/admin/ofertas'
    | '/admin/usuarios'
    | '/vehiculo/$id'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/contacto'
    | '/favoritos'
    | '/login'
    | '/mis-anuncios'
    | '/ofertas'
    | '/perfil'
    | '/publicar'
    | '/terminos'
    | '/admin/anuncios'
    | '/admin/contactos'
    | '/admin/ofertas'
    | '/admin/usuarios'
    | '/vehiculo/$id'
    | '/admin'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalogo'
    | '/contacto'
    | '/favoritos'
    | '/login'
    | '/mis-anuncios'
    | '/ofertas'
    | '/perfil'
    | '/publicar'
    | '/terminos'
    | '/admin/anuncios'
    | '/admin/contactos'
    | '/admin/ofertas'
    | '/admin/usuarios'
    | '/vehiculo/$id'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CatalogoRoute: typeof CatalogoRoute
  ContactoRoute: typeof ContactoRoute
  FavoritosRoute: typeof FavoritosRoute
  LoginRoute: typeof LoginRoute
  MisAnunciosRoute: typeof MisAnunciosRoute
  OfertasRoute: typeof OfertasRoute
  PerfilRoute: typeof PerfilRoute
  PublicarRoute: typeof PublicarRoute
  TerminosRoute: typeof TerminosRoute
  VehiculoIdRoute: typeof VehiculoIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-anuncios': {
      id: '/mis-anuncios'
      path: '/mis-anuncios'
      fullPath: '/mis-anuncios'
      preLoaderRoute: typeof MisAnunciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas': {
      id: '/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof OfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicar': {
      id: '/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof PublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/anuncios': {
      id: '/admin/anuncios'
      path: '/anuncios'
      fullPath: '/admin/anuncios'
      preLoaderRoute: typeof AdminAnunciosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contactos': {
      id: '/admin/contactos'
      path: '/contactos'
      fullPath: '/admin/contactos'
      preLoaderRoute: typeof AdminContactosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ofertas': {
      id: '/admin/ofertas'
      path: '/ofertas'
      fullPath: '/admin/ofertas'
      preLoaderRoute: typeof AdminOfertasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vehiculo/$id': {
      id: '/vehiculo/$id'
      path: '/vehiculo/$id'
      fullPath: '/vehiculo/$id'
      preLoaderRoute: typeof VehiculoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnunciosRoute: typeof AdminAnunciosRoute
  AdminContactosRoute: typeof AdminContactosRoute
  AdminOfertasRoute: typeof AdminOfertasRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnunciosRoute: AdminAnunciosRoute,
  AdminContactosRoute: AdminContactosRoute,
  AdminOfertasRoute: AdminOfertasRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CatalogoRoute: CatalogoRoute,
  ContactoRoute: ContactoRoute,
  FavoritosRoute: FavoritosRoute,
  LoginRoute: LoginRoute,
  MisAnunciosRoute: MisAnunciosRoute,
  OfertasRoute: OfertasRoute,
  PerfilRoute: PerfilRoute,
  PublicarRoute: PublicarRoute,
  TerminosRoute: TerminosRoute,
  VehiculoIdRoute: VehiculoIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
